-- ATE colab chat + idébox (showroom Supabase: oeppjpbaafjsowecyjho)
-- Run once in Supabase SQL Editor → https://supabase.com/dashboard/project/oeppjpbaafjsowecyjho/sql/new

create table if not exists public.ate_messages (
  id bigint generated by default as identity primary key,
  member text not null,
  body text not null,
  created_at timestamptz not null default now(),
  wiki_synced_at timestamptz,
  wiki_sync_error text
);

create table if not exists public.ate_ideas (
  id bigint generated by default as identity primary key,
  member text not null,
  body text not null,
  created_at timestamptz not null default now(),
  wiki_synced_at timestamptz,
  wiki_sync_error text
);

alter table public.ate_messages enable row level security;
alter table public.ate_ideas enable row level security;

create index if not exists ate_messages_created_idx on public.ate_messages (created_at desc);
create index if not exists ate_ideas_created_idx on public.ate_ideas (created_at desc);

-- API uses service role (Vercel); no anon policies needed for colab.
