-- TwistedStacks contact form submissions.
-- Stored server-side; written by Vercel /api/contact with the service-role key.
-- No direct browser access (RLS enabled, no anon policies).

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,

  -- Who wrote in (validated server-side: non-empty, trimmed, length-bounded).
  name        text        not null check (char_length(name) between 1 and 120),
  email       text        not null check (char_length(email) between 3 and 254)
                          and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$',
  company     text        check (company is null or char_length(company) <= 160),

  -- Where the form was opened from — REVISION demo, contact FAB, vault, etc.
  topic       text        not null check (char_length(topic) between 1 and 80),
  intent      text        not null check (intent in ('demo', 'feedback', 'bug', 'query')),

  -- Free-form body (already trimmed, max ~4 KB).
  message     text        not null check (char_length(message) between 1 and 4000),

  -- Lightweight audit trail for spam triage.
  source_url  text,
  referrer    text,
  user_agent  text,
  ip          inet,
  locale      text        check (locale is null or char_length(locale) <= 8),

  -- Email-forwarding outcome (NULL until the worker tries Resend).
  forwarded_at      timestamptz,
  forward_provider  text,
  forward_error     text,

  created_at  timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

-- No anon / authenticated policies on purpose: all reads go through
-- Vercel /api/contact with the service-role key. Keeps customer PII off the wire.

create index if not exists contact_submissions_created_idx
  on public.contact_submissions (created_at desc);

create index if not exists contact_submissions_topic_idx
  on public.contact_submissions (topic, created_at desc);

create index if not exists contact_submissions_email_idx
  on public.contact_submissions (email);
