create table if not exists public.pongg_scores (
  id bigint generated by default as identity primary key,
  name text not null check (name ~ '^[A-Z0-9]{1,6}$'),
  score integer not null check (score between 1 and 10000000),
  level integer not null check (level between 1 and 9),
  outcome text not null check (outcome in ('lost', 'champion')),
  created_at timestamptz not null default now()
);

alter table public.pongg_scores enable row level security;

drop policy if exists "Public can read Pongg leaderboard" on public.pongg_scores;
create policy "Public can read Pongg leaderboard"
  on public.pongg_scores
  for select
  using (true);

drop policy if exists "Public can submit Pongg scores" on public.pongg_scores;
create policy "Public can submit Pongg scores"
  on public.pongg_scores
  for insert
  with check (
    name ~ '^[A-Z0-9]{1,6}$'
    and score between 1 and 10000000
    and level between 1 and 9
    and outcome in ('lost', 'champion')
  );

create index if not exists pongg_scores_rank_idx
  on public.pongg_scores (score desc, level desc, created_at asc);
