-- SPACE team room chat — single shared thread.
-- Written/read by Vercel /api/space/chat with the service-role key.
-- No direct browser access (RLS enabled, no anon policies).

create table if not exists public.space_messages (
  id bigint generated by default as identity primary key,
  member text not null check (member in ('per', 'joachim', 'guest')),
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.space_messages enable row level security;

create index if not exists space_messages_created_idx
  on public.space_messages (created_at desc);
