-- SPACE team room idébox — quick idea dumps (dev tool).
-- Written/read by Vercel /api/space/ideas with the service-role key.
-- No direct browser access (RLS enabled, no anon policies).

create table if not exists public.space_ideas (
  id bigint generated by default as identity primary key,
  member text not null check (member in ('per', 'joachim', 'guest')),
  body text not null check (char_length(body) between 1 and 8000),
  created_at timestamptz not null default now()
);

alter table public.space_ideas enable row level security;

create index if not exists space_ideas_created_idx
  on public.space_ideas (created_at desc);
