-- SPACE session waitlist — signup for Blender/Unity/Commons sessions.
-- Written/read by Vercel /api/space/sessions with the service-role key.

create table if not exists public.space_session_signups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (char_length(email) between 3 and 200),
  interest text not null check (interest in ('blender', 'unity', 'commons', 'any')),
  preferred_slot text check (preferred_slot is null or char_length(preferred_slot) <= 120),
  note text check (note is null or char_length(note) <= 2000),
  created_at timestamptz not null default now()
);

alter table public.space_session_signups enable row level security;

create index if not exists space_session_signups_created_idx
  on public.space_session_signups (created_at desc);
