-- SUPARAYS team room idébox — quick idea dumps (dev tool).
-- Written/read by Vercel /api/suparays/ideas with the service-role key.
-- No direct browser access (RLS enabled, no anon policies).

create table if not exists public.suparays_ideas (
  id bigint generated by default as identity primary key,
  member text not null check (member in ('baha', 'kris', 'joachim', 'per')),
  body text not null check (char_length(body) between 1 and 8000),
  created_at timestamptz not null default now()
);

alter table public.suparays_ideas enable row level security;

create index if not exists suparays_ideas_created_idx
  on public.suparays_ideas (created_at desc);
