-- SUPARAYS team room shared files (metadata).
-- Blobs live in Supabase Storage bucket `suparays-shared` (private).
-- Upload/download via Vercel /api/suparays/files with service-role key.

insert into storage.buckets (id, name, public, file_size_limit)
values ('suparays-shared', 'suparays-shared', false, 26214400)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit;

create table if not exists public.suparays_files (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  original_name text not null check (char_length(original_name) between 1 and 200),
  member text not null check (member in ('baha', 'kris', 'joachim', 'per')),
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  content_type text check (content_type is null or char_length(content_type) <= 120),
  created_at timestamptz not null default now()
);

alter table public.suparays_files enable row level security;

create index if not exists suparays_files_created_idx
  on public.suparays_files (created_at desc);
